CREATE TABLE ADMINLOGIN (
	SL INT PRIMARY KEY IDENTITY(1,1), USER_NAME VARCHAR(10), PASSWORD VARCHAR(10) NOT NULL UNIQUE 
);
/*LOGIN TABLE CREATE CONNET WITH LOGIN FORM TO MATCH USER_ID AND PASSWORD TO ALLOW LOGIN
IDENTITY IS USE TO AUTO INCREMENT THE SL VALUE
*/

INSERT INTO ADMINLOGIN VALUES(
'TUSHAR','123456'
);

INSERT INTO ADMINLOGIN VALUES(
'ABDUL','787878'
);


SELECT *FROM ADMINLOGIN;