use SuperShopDB;

CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY NOT NULL IDENTITY(202010,1), CUSTOMER_NAME VARCHAR(20), ADDRESS VARCHAR(20),
EMAIL VARCHAR(15), PHONE VARCHAR(11), MEMBERSHIP_DATE DATE); 
/*CREATE CUSTOMER TABLE*/

