CREATE TABLE LOGIN (
	SL INT PRIMARY KEY IDENTITY(1,1), USER_ID VARCHAR(10), PASSWORD VARCHAR(10) NOT NULL UNIQUE, ROLE VARCHAR(10)
);
/*LOGIN TABLE CREATE CONNET WITH LOGIN FORM TO MATCH USER_ID AND PASSWORD TO ALLOW LOGIN
IDENTITY IS USE TO AUTO INCREMENT THE SL VALUE
*/

INSERT INTO LOGIN VALUES(
'TUS202001','123456','ADMIN'
);

INSERT INTO LOGIN VALUES(
'ABD202002','787878','SALESMAN'
);

INSERT INTO LOGIN VALUES(
'HOS202003','787758','SALESMAN'
);


SELECT *FROM LOGIN;